app:
    resource: "@AppBundle/Controller/"
    type:     annotation

index:
    resource: AppBundle\RestController\DefaultRestController
    type: rest
    prefix: /api

search:
    resource: AppBundle\RestController\SearchRestController
    type: rest
    prefix: /api

card_price:
    resource: AppBundle\RestController\CardPriceRestController
    type: rest
    prefix: /api
